### ISSUE TITLE
Fails to load with latest version of Mod Menu

### ISSUE THREAD

**Issue by DJBaphomet** [ToBinio/better-snow-coverage#4]
![image](https://github.com/user-attachments/assets/043fe870-aef0-4a76-9ff0-b0c77de06b9c)

[latest.log](https://github.com/user-attachments/files/16751425/latest.log)

**Comment by ToBinio** [comment]
fixed in [0.2.0](https://modrinth.com/mod/better-snow-coverage/version/0.2.0+mc1.21.0) thanks for reporting!

**Comment by ToBinio** [comment]
small note: i had to take down 0.2 since it seems to be complity brocken... see #5 for more info
