### ISSUE TITLE
Mod won't fix snowlogged grass renders despite absence of Continuity

### ISSUE THREAD

**Issue by Lumguava** [ToBinio/better-snow-coverage#6]
Hi! I just wanted to report that the mod wouldn't function with or without Continuity on a world with Wilder Wilds installed. I tried to also disable snowlogging in the other mod but it did more harm by breaking the textures so I would rather need this mod to work properly than to destroy a world file...

Below are the list of mods I installed. I am using **1.21.1** with **Fabric Loader 0.16.5**

[modlist.txt](https://github.com/user-attachments/files/17166577/modlist.txt)

Screenshots:
![image1](https://github.com/user-attachments/assets/9dd0f4f0-baa5-4209-8c19-9abedcb3145e)
![image2](https://github.com/user-attachments/assets/f908c5d6-5967-4305-bc46-3fc34dac26a0)
![image3](https://github.com/user-attachments/assets/dee6acaf-5a83-4ea9-aad9-427d0feec0e2)
![image4](https://github.com/user-attachments/assets/aaa91c87-9376-4930-b6e7-348f7c4f0abc)

**Comment by ToBinio** [comment]
better snow coverage 0.2.0 only works with sodium 0.6

you need to either use 0.1 of the mod (there weren't any major changes in 0.2 besides supporting sodium 0.6) 
or upgrade sodium to 0.6

this should fix your problem, let me know if it doesn't!

**Comment by Lumguava** [comment]
Hello! Thanks for replying. I've been informed that the Indium mod will not be needed anymore for Sodium 0.6 and above. Tested out removing Indium and it seemed to have solved my Sodium 0.6 beta crashed and fixed the snowlogging textures as well!

So far, no issues were found during 5 hours of gameplay (without Indium and with Sodium 0.6) since I've done the steps.

Still, thank you so much for your time! I appreciate the help.

**Comment by Lumguava** [comment]
Hello! Thanks for replying. I've been informed that the Indium mod will not be needed anymore for Sodium 0.6 and above. Tested out removing Indium and it seemed to have solved my Sodium 0.6 beta crash issues and fixed the snowlogging textures as well!

So far, no issues were found during 5 hours of gameplay (without Indium and with Sodium 0.6) since I've done the steps.

Still, thank you so much for your time! I appreciate the help.
