### ISSUE TITLE
1.20.1 Fabric Support

### ISSUE THREAD

**Issue by VoidLock92** [ToBinio/better-snow-coverage#7]
1.20.1 would be awesome. It is a very supported version of MC for mods. So I think a lot of people are using it still.

**Comment by ToBinio** [comment]
Will work on this in the coming days.

**Comment by VoidLock92** [comment]
Awesome! thank you so much :) I am looking forward to it!

**Comment by ToBinio** [comment]
https://modrinth.com/mod/better-snow-coverage/version/0.2.0+mc1.20.1

I believe it should work, in case you run into any issues please let me know!

thanks for giving my mod a try!

small note:
I will probably backport denseFlowers tomorrow

**Comment by ToBinio** [comment]
happy to hear that!

> Without it the plants look so silly in snow areas.

i fully agree
